## Cleann temporary folder every monday at 12pm
temporary:
   folder: /tmp/crusoe/temporary
   cronExpression: 0 0 12 ? * MON 
   storageDuration: 2

server:
    port: 8485
    max-http-header-size: 128000
spring:
   data.mongodb:
      host: localhost
      port: 27017
      database: crusoe
      username: crusoe
      password: ${MONGODB_PASSWORD}
   servlet:
      multipart:
         max-file-size: 25MB
         max-request-size: 25MB
   profiles:
      include:
      - local
      
logging:
   file: ../logs/crusoe-preprod.log
   
tmpFolder: /tmp/crusoe/tmp
      
management:
    port: 8081

mail:
   hostname: localhost
   subjectPrefix: '[Crusöe]'
   from: noreply@crusoe.fr
   

orcid:
   tokenUrl: https://orcid.org/oauth/token
   publicApiUrl: https://pub.orcid.org/v2.1

shibboleth:
   url: https://services-coso-preprod.sedoo.fr
        
ftp:
    host: sedur.sedoo.fr
    username: crusoe
    password: ${FTP_PASSWORD}

## check for notification (no activity on a repo) Every Monday at noon
notification:
    cronExpression: 0 0 12 ? * MON 
    unused.report.months.delay: 2

## Update statistics Every day at noon - 12pm
statistics:
    cronExpression: 0 0 12 * * ?
    
app.url: http://localhost:8080


english.header: See below for the English translation.

create.user.notification.subject: Votre compte CRUSÖE a été créé / Your CRUSÖE account has been created
create.user.notification.orcid.fr.content: <p>Cher collègue,</p><p>Vous pouvez vous connecter en utilisant votre orcid %s.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
create.user.notification.renater.fr.content: <p>Cher collègue,</p><p>Vous pouvez vous connecter en utilisant votre courriel Renater %s.</p><p>Si ce n'est pas votre courriel Renater veuillez contacter un administrateur via le menu contact du site.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
create.user.notification.orcid.en.content: <p>Dear colleague,</p><p>You have now a CRUSÖE account. Log in using your orcid %s.</p><p>Best regards,</p><p>CRUSÖE administrator team</p>
create.user.notification.renater.en.content: <p>Dear colleague,</p><p>You have now a CRUSÖE account. Log in using your renater email %s.</p><p>If there is not your Renater email, please contact an administrator using the contact menu on the web site.</p><p>Best regards,</p><p>CRUSÖE administrator team</p>

add.user.notification.subject: Accès à l'entrepôt %s accordé / %s repository access granted
add.user.notification.fr.content: <p>Cher collègue,</p><p>Vous avez maintenant accès à l'entrepôt %s avec le rôle %s.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
add.user.notification.en.content: <p>Dear colleague,</p><p>You have now access to %s repository with %s role.</p><p>Best regards,</p><p>CRUSÖE administrator team</p>

remove.user.notification.subject: Accès à l'entrepôt %s révoqué / %s repository access removed
remove.user.notification.fr.content: <p>Cher collègue,</p><p>Votre permission d'accès à l'entrepôt %s vous a été enlévée.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
remove.user.notification.en.content: <p>Dear colleague,</p><p>You have been removed from %s repository.</p><p>Best regards,</p><p>CRUSÖE administrator team</p>

declined.user.notification.subject: Demande d'accès à l'entrepôt %s refusée / %s repository access request has been declined
declined.user.notification.fr.content: <p>Cher collègue,</p><p>Votre demande d'accès à l'entrepôt %s vous a été refusée.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
declined.user.notification.en.content: <p>Dear colleague,</p><p>Your request on %s repository has been declined.</p><p>Best regards,</p><p>CRUSÖE administrator team</p>

report.validation.notification.subject: Un dossier de certification a été figé pour l'entrepôt %s / A report has been frozen on the %s repository
report.validation.notification.fr.content: <p>Cher collègues,</p><p>Un nouveau dossier de certification a été figé pour l'entrepôt %s.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
report.validation.notification.en.content: <p>Dear colleagues,</p><p>A new report has been frozen on the %s repository.</p><p>Best regards,</p><p>CRUSÖE administrator team</p>

report.new.version.notification.subject: Nouvelle version du dossier de certification sur l'entrepôt %s / New report version available on %s repository
report.new.version.notification.fr.content: <p>Cher collègues,</p><p>Une nouvelle version du dossier de certification est disponible pour l'entrepôt %s.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
report.new.version.notification.en.content: <p>Dear colleagues,</p><p>A new report version is available on %s repository.</p><p>Best regards,</p><p>CRUSÖE administrator team</p>

new.comment.notification.subject: Nouveau commentaire sur l'entrepôt %s / New comment has been posted on %s repository
new.comment.notification.fr.content: <p>Cher collègues,</p><p>Un commentaire a été posté pour l'entrepôt %s.</p><p>%s</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
new.comment.notification.en.content: <p>Dear colleagues,</p><p>A new comment has been posted on %s repository.</p><p>%s</p><p>Best regards,</p><p>CRUSÖE administrator team</p>

repository.access.request.subject: Demande d'access à l'entrepôt %s / Access has been request on %s repository
repository.access.request.fr.content: <p>Cher collègue,</p><p>%s (%s) a demandé le rôle %s sur l'entrepôt %s.</p><p>%s</p><p>Message de l'utilisateur:%s</p>
repository.access.request.en.content: <p>Dear colleague,</p><p> %s (%s) has requested %s role on %s repository.</p><p>%s</p><p> User message:</p><p>%s</p>

no.activity.subject: Un dossier de certification de l'entrepôt %s n'a pas été mis à jour depuis %s mois / A %s repository report has not been updated for %s months
no.activity.fr.content: <p>Cher collègue,</p><p>Pour information, il n'y a eu aucune activité sur votre dossier de certification %s de l'entrepôt %s depuis %s mois.</p><p>Si votre auto-évaluation est terminée vous pouvez utiliser 'Figer cette version' pour la finaliser en rendant ce dossier de certification non modifiable. Vous ne recevrez alors plus de rappel. Vous pourrez créer un nouveau dossier de certification en partant de cette version si besoin.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
no.activity.en.content: <p>Dear colleagues,</p><p>For you information, no update has been made on your report %s on %s repository for the last %s months.</p>If your self assessment is over you can use the button 'Freeze this version' to finalize it by making the report unchangeable. You will not receive reminder anymore. You will be able to create a new assessment report based on this version if you need.<p></p><p>Best regards,</p><p>CRUSÖE administrator team</p>

---

spring.profiles: dev
      
notification.cronExpression: 0 * * ? * *

---

spring.profiles: docker

spring:
   data.mongodb:
      port: 27017
      host: container-mongodb
      
ftp:
    host: container-ftp-server
    
mail:
   hostname: container-smtp

---

spring.profiles: distant-preprod

spring:
   data.mongodb:
      host: localhost
      port: 27018
      database: crusoe-preprod
      username: crusoe-preprod
      
---

spring.profiles: distant-prod

spring:
   data.mongodb:
      host: localhost
      port: 27019
      database: crusoe
      username: crusoe
      
---

spring.profiles: prod
spring:
   data.mongodb:
      host: 193.52.225.51
      database: crusoe
      username: crusoe
        
tmpFolder: /export1/crusoe/tmp

app.url: https://crusoe.ouvrirlascience.fr/application

logging:
   file: ../logs/crusoe-prod.log
        
---

spring.profiles: preprod
spring:
   data.mongodb:
      host: 193.52.225.51
      database: crusoe-preprod
      username: crusoe-preprod

ftp:
    username: crusoepreprod
    password: ${FTP_PASSWORD}

tmpFolder: /export1/crusoe-preprod/tmp

app.url: https://coso-preprod.sedoo.fr/application


        
