eureka:
  client:
    enabled: false
    
endpoints:
    enabled: true
    health:
        enabled: true

## Cleann temporary folder every monday at 12pm
temporary:
   folder: /tmp/crusoe/temporary
   cronExpression: 0 0 12 ? * MON
   storageDuration: 2
   
cors.allowed.origins: http://127.0.0.1:8080,http://localhost:8080,https://www.sedoo.fr,https://crusoe.ouvrirlascience.fr,https://coso-preprod.sedoo.fr

jwt:
    signingKey: ENC(Kk3QSFlnhwMd12IEt59oezOtQSHExg4S)
    token.validity: ENC(NbVr8F4ZCg9gBHKnHCG4Pw==)
    token.access.resquest.validity: ENC(8m6zgGXwCHmpL55OswN4BQ==)

server:
    port: 8485
    max-http-header-size: 128000
spring:
   data.mongodb:
      host: localhost
      port: 27017
      database: crusoe
      username: ENC(UQhjsOY6PLd80nd1PB+M6Q==)
      password: ENC(Fn87XueUaQubl7mbo5F4/g==)
   servlet:
      multipart:
         max-file-size: 25MB
         max-request-size: 25MB
   profiles:
      include:
      - local
   
tmpFolder: /tmp/crusoe/tmp
      
management:
    port: 8081

mail:
   hostname: localhost
   subjectPrefix: '[CRUSOE]'
   from: noreply@crusoe.fr
   

orcid:
   clientId: ENC(UuDEqoj+3WyNszUmqf5T89rluQ4DCxUE2hPdW6YXF0g=)
   clientSecret: ENC(y22Q4f2wYjFi8UGYt1+FARfqlXIx57PMO8QUrUSlLpTH9Qjc0yzcLs92LaoDyUM9)
   tokenUrl: https://orcid.org/oauth/token
   publicApiUrl: https://pub.orcid.org/v2.1
   superAdmins: ENC(efNcA98YIW08HO8ovT2zNRnFaQ1ZQH/QsA5xt3WoMkzJrc/PceFJNT2X1FGLSKM/)
   admins: ENC(o8Xje/otTEQEDxTE5phNAphH9C68/gHVRdXzvfkH1dldevsxlfA+F+1EQzntizm/dijDzECFK+7xbuop2+vh/ttj6H01ee0+tKV1atkkN/KHkxQGiQ+I5A==)

shibboleth:
   url: https://services-shib.sedoo.fr
        
ftp:
    host: sedur.sedoo.fr
    username: ENC(+OrYdf9k5Ec1YllPehstqA==)
    password: ENC(BTqmeqii32r8gGeY7X+NKwVSGwK884y+)

## check for notification (no activity on a repo) Every Monday at noon
notification:
    cronExpression: 0 0 12 ? * MON 
    unused.report.months.delay: 2
    enabled: true

## Update statistics Every day at noon - 12pm
statistics:
    cronExpression: 0 0 12 * * ?
    
app.url: http://localhost:8080

springdoc:
  server.url: http://localhost:${server.port}/
  oAuthFlow:
    authorizationUrl: http://localhost:8485/auth/v1_0/signin
    tokenUrl: http://localhost:8485/auth/v1_0/login


english.header: See below for the English translation.

create.user.notification.subject: Votre compte CRUSÖE a été créé / Your CRUSÖE account has been created
create.user.notification.orcid.fr.content: <p>Cher collègue,</p><p>Vous pouvez vous connecter en utilisant votre orcid %s.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSOE</p>
create.user.notification.renater.fr.content: <p>Cher collègue,</p><p>Vous pouvez vous connecter en utilisant votre courriel Renater %s.</p><p>Si ce n'est pas votre courriel Renater veuillez contacter un administrateur via le menu contact du site.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSOE</p>
create.user.notification.orcid.en.content: <p>Dear colleague,</p><p>You have now a CRUSOE account. Log in using your orcid %s.</p><p>Best regards,</p><p>CRUSOE administrator team</p>
create.user.notification.renater.en.content: <p>Dear colleague,</p><p>You have now a CRUSOE account. Log in using your renater email %s.</p><p>If there is not your Renater email, please contact an administrator using the contact menu on the web site.</p><p>Best regards,</p><p>CRUSOE administrator team</p>

add.user.notification.subject: Accès à l'entrepôt %s accordé / %s repository access granted
add.user.notification.fr.content: <p>Cher collègue,</p><p>Vous avez maintenant accès à l'entrepôt %s avec le rôle %s.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
add.user.notification.en.content: <p>Dear colleague,</p><p>You have now access to %s repository with %s role.</p><p>Best regards,</p><p>CRUSÖE administrator team</p>

remove.user.notification.subject: Accès à l'entrepôt %s révoqué / %s repository access removed
remove.user.notification.fr.content: <p>Cher collègue,</p><p>Votre permission d'accès à l'entrepôt %s vous a été enlévée.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
remove.user.notification.en.content: <p>Dear colleague,</p><p>You have been removed from %s repository.</p><p>Best regards,</p><p>CRUSÖE administrator team</p>

declined.user.notification.subject: Demande d'accès à l'entrepôt %s refusée / %s repository access request has been declined
declined.user.notification.fr.content: <p>Cher collègue,</p><p>Votre demande d'accès à l'entrepôt %s vous a été refusée.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
declined.user.notification.en.content: <p>Dear colleague,</p><p>Your request on %s repository has been declined.</p><p>Best regards,</p><p>CRUSÖE administrator team</p>

report.validation.notification.subject: Un dossier de certification a été figé pour l'entrepôt %s / A report has been frozen on the %s repository
report.validation.notification.fr.content: <p>Cher collègues,</p><p>Un nouveau dossier de certification a été figé pour l'entrepôt %s.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
report.validation.notification.en.content: <p>Dear colleagues,</p><p>A new report has been frozen on the %s repository.</p><p>Best regards,</p><p>CRUSÖE administrator team</p>

report.new.version.notification.subject: Nouvelle version du dossier de certification sur l'entrepôt %s / New report version available on %s repository
report.new.version.notification.fr.content: <p>Cher collègues,</p><p>Une nouvelle version du dossier de certification est disponible pour l'entrepôt %s.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
report.new.version.notification.en.content: <p>Dear colleagues,</p><p>A new report version is available on %s repository.</p><p>Best regards,</p><p>CRUSÖE administrator team</p>

new.comment.notification.subject: Nouveau commentaire sur l'entrepôt %s / New comment has been posted on %s repository
new.comment.notification.fr.content: <p>Cher collègues,</p><p>Un commentaire a été posté pour l'entrepôt %s.</p><p>%s</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
new.comment.notification.en.content: <p>Dear colleagues,</p><p>A new comment has been posted on %s repository.</p><p>%s</p><p>Best regards,</p><p>CRUSÖE administrator team</p>

repository.access.request.subject: Demande d'access à l'entrepôt %s / Access has been request on %s repository
repository.access.request.fr.content: <p>Cher collègue,</p><p>%s (%s) a demandé le rôle %s sur l'entrepôt %s.</p><p>%s</p><p>Message de l'utilisateur:%s</p>
repository.access.request.en.content: <p>Dear colleague,</p><p> %s (%s) has requested %s role on %s repository.</p><p>%s</p><p> User message:</p><p>%s</p>

no.activity.subject: Un dossier de certification de l'entrepôt %s n'a pas été mis à jour depuis %s mois / A %s repository report has not been updated for %s months
no.activity.fr.content: <p>Cher collègue,</p><p>Pour information, il n'y a eu aucune activité sur votre dossier de certification %s de l'entrepôt %s depuis %s mois.</p><p>Si votre auto-évaluation est terminée vous pouvez utiliser 'Figer cette version' pour la finaliser en rendant ce dossier de certification non modifiable. Vous ne recevrez alors plus de rappel. Vous pourrez créer un nouveau dossier de certification en partant de cette version si besoin.</p><p>Bien cordialement,</p><p>L'équipe d'administration de CRUSÖE</p>
no.activity.en.content: <p>Dear colleagues,</p><p>For you information, no update has been made on your report %s on %s repository for the last %s months.</p>If your self assessment is over you can use the button 'Freeze this version' to finalize it by making the report unchangeable. You will not receive reminder anymore. You will be able to create a new assessment report based on this version if you need.<p></p><p>Best regards,</p><p>CRUSÖE administrator team</p>

---

spring:
   config.activate.on-profile: dev
      
notification.cronExpression: 0 * * ? * *

---

spring:
   config.activate.on-profile: distant-preprod
   data.mongodb:
      host: localhost
      port: 27018
      database: crusoe-preprod
      username: ENC(dd++TAvuVjOhnL/nazq20rEvIgVKT6F9)
      
---

spring:
   config.activate.on-profile: distant-prod
   data.mongodb:
      host: localhost
      port: 27018
      database: crusoe
      username: ENC(xDG3WKOeQqaxxS1ywUAOLQ==)
      
---

spring:
   config.activate.on-profile: prod
   data.mongodb:
      host: ENC(VxaOpB6o02ylzWwZDXmZ4gNwbFSPOwfL)
      database: crusoe
      username: ENC(xDG3WKOeQqaxxS1ywUAOLQ==)

server:
  port: 0

ftp.password: ENC(kShx0LIsDEHIyQSf+BZuZDig3TCD8z8k)
tmpFolder: ${application.folder}/tmp

app.url: https://crusoe.ouvrirlascience.fr/application
        
---

spring:
   config.activate.on-profile: preprod
   data.mongodb:
      host: ENC(BkGnjmgEm4DhGG/euQpbVqZEqqVy1ImJ)
      database: crusoe-preprod
      username: ENC(GHG9Tv3+Vt+/ivCecy52KsZ+fp892RR7)


server:
  port: 0
  
notification.enabled: false

ftp:
    username: crusoepreprod
    password: ENC(WwjTuYoQmEziqKQmXDCJ0KvXrZgBKS2l)

tmpFolder: ${application.folder}/tmp

app.url: https://coso-preprod.sedoo.fr/application

---
spring:
   config.activate.on-profile: monitoring
   cloud:
      discovery:
         enabled: true
       
info:
  api: https://api.sedoo.fr/${spring.application.name}/swagger-ui/index.html
  code:
    front: https://github.com/sedoo/certifymyrepo-back
    back: https://github.com/sedoo/certifymyrepo
  folders: ${tmpFolder}
  database:
    type: MongoDB
    location: SEDUR
  archive: none
  authentication: ${shibboleth.url}
  ftp: ${ftp.host}
         
endpoints:
    enabled: true
    health:
        enabled: true
management:
    info.env.enabled: true
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
        health:
            show-details: "ALWAYS"
            northstar:
                cacheup: 240
                cachedown: 120 

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone:  http://ada:8761/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
 
springdoc:
  oAuthFlow:
    authorizationUrl:
    tokenUrl: https://api.sedoo.fr/${spring.application.name}/auth/v1_0/signin
  swagger-ui:
    configUrl: /${spring.application.name}/v3/api-docs/swagger-config
    url: /${spring.application.name}/v3/api-docs/
  server.url:  https://api.sedoo.fr/${spring.application.name}

        
