temporary:
   folder: /tmp/crusoe/temporary
   cronExpression: 0 30 20 * * *
   storageDuration: 2

server:
    port: 8485
    max-http-header-size: 128000
spring:
   data.mongodb:
      host: localhost
      port: 27017
      database: crusoe
      username: crusoe
      password: ${MONGODB_PASSWORD}
   servlet:
      multipart:
         max-file-size: 10MB
         max-request-size: 10MB
   profiles:
      include:
      - local
      
logging:
   file: ../logs/crusoe-preprod.log
   
tmpFolder: /tmp/crusoe/tmp
      
management:
    port: 8081

mail:
   hostname: localhost
   subjectPrefix: '[Crusöe]'
   from: noreply@crusoe.fr
   

orcid:
   tokenUrl: https://orcid.org/oauth/token
   publicApiUrl: https://pub.orcid.org/v2.1

shibboleth:
   url: https://services-coso-preprod.sedoo.fr
        
ftp:
    host: sedur.sedoo.fr
    username: crusoe

notification:
    cronExpression: 0 30 20 * * *
    unused.report.months.delay: 2
    
app.url: http://localhost:8080


english.header: See below for the English translation.

create.user.notification.subject: Votre compte CRUSÖE a été créé / You CRUSÖE account has been created
create.user.notification.orcid.fr.content: <p>Cher collègue,</p><p>Vous pouvez vous connecter en utilisant votre orcid %s.</p><p>Bien cordialement,</p><p>L'équipe COSO</p>
create.user.notification.renater.fr.content: <p>Cher collègue,</p><p>Vous pouvez vous connecter en utilisant votre courriel Renater %s.</p><p>Si ce n'est pas votre courriel Renater veuillez contacter un administrateur via le menu contact du site.</p><p>Bien cordialement,</p><p>L'équipe COSO</p>
create.user.notification.orcid.en.content: <p>Dear colleague,</p><p>You have now a CRUSÖE account. Log in using your orcid %s.</p><p>Best regards,</p><p>The COSO team</p>
create.user.notification.renater.en.content: <p>Dear colleague,</p><p>You have now a CRUSÖE account. Log in using your renater email %s.</p><p>If there is not your Renater email, please contact an administrator using the contact menu on the web site.</p><p>Best regards,</p><p>The COSO team</p>

add.user.notification.subject: Accès à l'entrepôt %s accordé / %s repository access granted
add.user.notification.fr.content: <p>Cher collègue,</p><p>Vous avez maintenant accès à l'entrepôt %s avec le rôle %s.</p><p>Bien cordialement,</p><p>L'équipe COSO</p>
add.user.notification.en.content: <p>Dear colleague,</p><p>You have now access to %s repository with %s role.</p><p>Best regards,</p><p>The COSO team</p>

remove.user.notification.subject: Accès à l'entrepôt %s révoqué / %s repository access removed
remove.user.notification.fr.content: <p>Cher collègue,</p><p>Votre permission d'accès à l'entrepôt %s vous a été enlévée.</p><p>Bien cordialement,</p><p>L'équipe COSO</p>
remove.user.notification.en.content: <p>Dear colleague,</p><p>You have been removed from %s repository.</p><p>Best regards,</p><p>The COSO team</p>

declined.user.notification.subject: Demande d'accès à l'entrepôt %s refusée / %s repository access request has been declined
declined.user.notification.fr.content: <p>Cher collègue,</p><p>Votre demande d'accès à l'entrepôt %s vous a été refusée.</p><p>Bien cordialement,</p><p>L'équipe COSO</p>
declined.user.notification.en.content: <p>Dear colleague,</p><p>Your request on %s repository has been declined.</p><p>Best regards,</p><p>The COSO team</p>

report.validation.notification.subject: Une fiche a été validé pour l'entrepôt %s / A report has been validated on the %s repository
report.validation.notification.fr.content: <p>Cher collègues,</p><p>Une nouvelle fiche a été validée pour l'entrepôt %s.</p><p>Bien cordialement,</p><p>L'équipe COSO</p>
report.validation.notification.en.content: <p>Dear colleagues,</p><p>A new report has been validated on the %s repository.</p><p>Best regards,</p><p>The COSO team</p>

report.new.version.notification.subject: Nouvelle version de fiche sur l'entrepôt %s / New report version available on %s repository
report.new.version.notification.fr.content: <p>Cher collègues,</p><p>Une nouvelle version de fiche est disponible pour l'entrepôt %s.</p><p>Bien cordialement,</p><p>L'équipe COSO</p>
report.new.version.notification.en.content: <p>Dear colleagues,</p><p>A new report version is available on %s repository.</p><p>Best regards,</p><p>The COSO team</p>

new.comment.notification.subject: Nouvel commentaire sur l'entrepôt %s / New comment has been posted on %s repository
new.comment.notification.fr.content: <p>Cher collègues,</p><p>Un commentaire a été posté pour l'entrepôt %s.</p><p>%s</p><p>Bien cordialement,</p><p>L'équipe COSO</p>
new.comment.notification.en.content: <p>Dear colleagues,</p><p>A new comment has been posted on %s repository.</p><p>%s</p><p>Best regards,</p><p>The COSO team</p>

repository.access.request.subject: Demande d'access à l'entrepôt %s / Access has been request on %s repository
repository.access.request.fr.content: <p>Cher collègue,</p><p>%s (%s) a demandé le rôle %s sur l'entrepôt %s.</p><p>%s</p><p>Message de l'utilisateur:%s</p>
repository.access.request.en.content: <p>Dear colleague,</p><p> %s (%s) has requested %s role on %s repository.</p><p>%s</p><p> User message:</p><p>%s</p>

no.activity.subject: L'entrepôt %s n'a pas été mis à jour depuis un moment / The repository %s has not been updated for a while
no.activity.fr.content: <p>Cher collègue,</p><p>Il n'y a eu aucunes activitées sur votre entrepôt %s depuis %s mois.</p><p>Bien cordialement,</p><p>L'équipe COSO</p>
no.activity.en.content: <p>Dear colleagues,</p><p>No update has been made on your %s repository for the last %s months.</p><p>Best regards,</p><p>The COSO team</p>

---

spring.profiles: dev
      
notification.cronExpression: 0 * * ? * *

---

spring.profiles: tunnelssh-preprod

spring:
   data.mongodb:
      host: localhost
      port: 27018
      database: crusoe-preprod
      username: crusoe-preprod
      
---

spring.profiles: prod
spring:
   data.mongodb:
      host: 193.52.225.51
      database: crusoe
        
tmpFolder: /export1/crusoe/tmp

app.url: https://coso.sedoo.fr/application
        
---

spring.profiles: preprod
spring:
   data.mongodb:
      host: 193.52.225.51
      database: crusoe-preprod
      username: crusoe-preprod

tmpFolder: /export1/crusoe-preprod/tmp

app.url: https://coso-preprod.sedoo.fr/application


        
